\documentclass[final]{beamer} % beamer 3.10: do NOT use option hyperref={pdfpagelabels=false} !
  %\documentclass[final,hyperref={pdfpagelabels=false}]{beamer} % beamer 3.07: get rid of beamer warnings
  \mode<presentation> { \usetheme{UFPoster} }
  \usepackage{multicol}
  \usepackage[english]{babel}
  \usepackage[latin1]{inputenc}
  \usepackage{amsmath,amsthm, amssymb, latexsym, todonotes}
  \usefonttheme[onlymath]{serif}
  \boldmath{}
  \usepackage[orientation=portrait,size=custom,height=114,width=121,scale=0.9,debug]{beamerposter}                       % e.g. for DIN-A0 poster
  \title{VALIDATING APPROACHES TO DETECTING HIDDEN SOCIAL GROUPS}
  \subtitle{contact \texttt{cap10@epi.ufl.edu} about this poster \texttt{https://github.com/pearsonca/epi\_research\_day2016}}
  \author{Carl A. B. Pearson\textsuperscript{1}, Burton H. Singer\textsuperscript{1}}
  \institute[EPI-UF]{\textsuperscript{1}Emerging Pathogens Institute, University of Florida}
  \date{\today}
  \newcommand{\spaceProp}{0.01}
  \newcommand{\spacer}{\begin{column}{\spaceProp\paperwidth}\end{column}}

  \newenvironment{oneCol}{\begin{column}[t]{0.24\paperwidth}}{\end{column}}
  \newenvironment{threeCol}{\begin{column}[t]{0.73\paperwidth}}{\end{column}}
  \setbeamertemplate{caption}[numbered]
\begin{document}
\SweaveOpts{concordance=TRUE}
  \begin{frame}{}
    \begin{columns}[t]
    \spacer{}
    \begin{oneCol}

\begin{block}{MOTIVATION}
Detecting small, covert groups embedded in a large, similar population is a methodological challenge.  These groups actively hide in the surrounding communities.  Unless they exhibit idiosyncratic behavior, detection is impossible.  However, how much idiosyncratic behavior is required to reliably identify them is an open question.
\end{block}

\begin{block}{DETECTION SCHEME}
For the results shown here, we considered a traditional social network analysis approach: community identification.  After embedding the synthetic group in wifi access time series, we
\begin{enumerate}
  \item divide the data set into intervals (non-overlapping 30 day windows in this case)
  \item compute the communities in each interval.  We use the fast-greedy heuristic algorithm.
  \item for each interval $t$, record if people $i$, $j$ are in the same community ($\delta_{ij}(t)=1$) or not ($\delta_{ij}(t)=0$)
  \item score persistent association between $i$, $j$ in an interval $t$ as
  $$
  S_{i,j}(t) = r\left(\delta_{ij}(t) + \sum_{n=1}^{t}\delta_{ij}(t-n)r^n\right)
  $$
  where $r$ is a discounting rate.  Also censor from further accumulation any $S_{i,j}(t)$ that falls below some threshold.  We use six intervals with no association ($S_{i,j}(t) < r^6$) for our threshold.
  \item In each interval, compute \emph{persistence communities} by assigning weighted edges between $i$, $j$ with score above some level, and then using a community identification algorithm that can leverage weighted edges (we use the spinglass community).  We use the discount rate as the cutoff: i.e., people that are at least as associated as appearing together in the current interval.
  \item all communities which are above the minimum community size (2) and below some cut-off (varied to trade-off sensitivity and specificity) are implicated as potential covert groups.
\end{enumerate}
\end{block}
\begin{block}{DISCUSSION}
Detection is hard.  We have not yet identified an approach that will reliably separate the covert members from the background population, and all approaches are computationally intensive.
\end{block}

\end{oneCol}
    \spacer{}
\begin{threeCol}
\begin{columns}[t]
\begin{column}{.31\linewidth}
  \begin{block}{APPROACH}
  We want to identify relative performance of various detection strategies against different covert group scenarios.  Characterizing groups that are not detectable by our methods is particularly important.

  We use a large empirical dataset of human activity (usage of a municipal wifi system in Montreal) as an example background population.  We demonstrate embedding a synthetic covert group into that data, and evaluate a method for detecting them.

  Work so far focused on deliberately concealed criminal groups, but methods should translate to missing populations in infectious disease questions.
  \end{block}
\end{column}
\begin{column}{.31\linewidth}
\begin{block}{COVERT GROUP}
  \begin{enumerate}
  \item categorize background population by their activity (see fig. X for categorization axes)
  \item select a background group as a template
  \item create a population, size $N_C$, which each member from that template
  \item define covert group interactions for that population
  \item simulate covert group ``normal'' and ``covert'' events
  \item synthesize background and simulated events
  \end{enumerate}
\end{block}
\end{column}
\begin{column}{.31\linewidth}
\begin{block}{ANALYSIS}
Any given detection method will entail sensitivity and specificity statistics, determinable since the covert group identity is known.  For any interval, the TPR and FPR are calculated based on: $N_C$, the number of covert members in the group; $C(t)$, the number of covert members correctly labeled in interval $t$; $N_B(t)$, the size of the background population considered in the interval (i.e., appearing in any community); and $B(t)$ the number of background individuals incorrectly labeled as covert members.  So TPR$(t)=\frac{C(t)}{N_C}$ and FPR$(t)=\frac{B(t)}{N_B(t)}$.
\end{block}
\end{column}
\end{columns}

\begin{block}{RESULTS}
  \begin{columns}
\begin{column}{.48\linewidth}
  \begin{figure}\centering
  \includegraphics{locationclusters.png}
  \caption{The locations in the wifi system, clustered by usage features.}
  \end{figure}
  \begin{figure}\centering
  \includegraphics{users.png}
  \caption{Users in the Montreal Municipal Wifi, by location preference and activity level.}
  \end{figure}
\end{column}
\begin{column}{.48\linewidth}
  \begin{figure}\centering
  \includegraphics{detection_results.png}
  \caption{Results of the proposed detection scheme applied to a synthetic group mimicing the most-typical group of the population: typical usage per time, some usage variability, tending to towards mid day usage (center panel fig. 2, green dots).  Members of the covert group additionally meet roughly once per week in a single location, of the type preferred by the population they are mimicing.  As should be clear, these individuals are not detectable at all.}
  \end{figure}
\end{column}
\end{columns}
    \end{block}

  \begin{block}{References}

    \footnotesize{\nocite{*}\bibliographystyle{unsrt}
    \bibliography{biblio}\vspace{0.75in}}

  \end{block}
\end{threeCol}
\spacer{}
\end{columns}
\end{frame}
\end{document}
